name = "PiecewiseIncreasingRanges"
uuid = "efdf428f-f294-58b6-a961-90c8051bff4c"
version = "0.0.5"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

[compat]
julia = "â‰¥ 1.0"

[extras]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Interpolations"]
